### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Rxbsxn** [Easiv/CoolWriter-backend#1]
# TODO - BACKEND FOR COOLWRITER
- [x] Setup rails project (Look how to create rails project for RAILS API, with PSQL DB)
- [x] Install jsonapi-resources gem
- [x] Setup specs (install rspec, factorybot, ffaker, database_cleaner, shoulda_matchers)
- [x] create resources & controllers (You can use cli from jsonapiresources)
- [x] set parameters/relationships in resources
- [x] Setup a CI (Travis || Codeship || CircleCi)
- [x] Write specs for controllers, every action should have a test
- [x] Set up CORS
- [ ] Move policy to backend (pundit)

## Models
- [x] Define models and relations
- [x] Write specs for models (Validations/relationship specs - use shoulda_matchers)

## relationships
![Relationships connections](https://user-images.githubusercontent.com/17426143/45213524-0f85cc00-b298-11e8-83f9-40ffe88c3252.png)

## properties from frontend (some of them are useless)
```js
// Book
export default Model.extend({
  cover: attr('string', { defaultValue: 'http://via.placeholder.com/200x300' }),
  title: attr('string') // Should be present, not shorter than 5 chars, should be uniq
  author: attr('string'),
  userEmail: attr('string'),
  description: attr('string') //
  pageCount: attr('number', { defaultValue: 0 }),
  pages: hasMany('page')
});
```

```js
// Page
export default Model.extend({
  content: attr('string'), // Not longer than 300chars
  book: belongsTo('book'), // book should be present
  bookId: attr('string')
});
```

```js
// User
export default Model.extend({
  name: attr('string'), 
  photoUrl: attr('string'),
  email: attr('string'), // should be valid email, uniq
  books: hasMany('book'),
  isAdmin: attr('boolean') // default false
});
```

## Additional tasks
- [ ] Create mailer which will be sent to the author of the book, after book creation. The mailer should contain book name, author name
- [ ] Create service, which will send email to all authors without books, the mailer should be sent once a week. Mailer should contain Author's name and simple reminder (Patterns::Service, Query object, sidekick, HAML)
